title = "/home/mole"
description = "Creations and ramblings of Mikael \"Molentum\" Myyrä."
base_url = "https://molentum.me"
default_language = "en"

generate_feeds = true
feed_filenames = ["rss.xml"]
compile_sass = true
build_search_index = false
# source.md are files with LaTeX,
# which I manually render into index.md files with HTML math
ignored_content = ["**/source.md"]

theme = "zerm"

taxonomies = [{ name = "tags" }, { name = "characters" }]

[markdown]
highlight_code = true

[extra]
favicon = "favicon.ico"
og_preview_img = "self_square.jpg"

author = "Mikael Myyrä"
copyright = "Mikael Myyrä"
show_author = false
show_tags = true
show_categories = true
logo_text = "/home/mole"
read_more = "read more"
main_menu = [
  { url = "/about/", name = "about" },
  { url = "/blog/", name = "blog" },
  { url = "/gallery/", name = "gallery" },
  { url = "/notes/", name = "notes" },
  { url = "https://mastoart.social/@molentum", name = "Mastodon", external = true, rel_me = true },
  { url = "https://github.com/m0lentum", name = "GitHub", external = true, rel_me = true },
  { url = "https://molentum.itch.io/", name = "Itch.io", external = true },
]
fedi_account = "@molentum@mastoart.social"
webmention_target = "https://webmention.io/molentum.me/webmention"

# custom color defined in my own sass dir
theme_color = "lime"
center = true
custom_css = true
