title = "Mole's Nerd Cave"
description = "Code, math, physics, graphics, games, art, music, and not enough time."
base_url = "https://moletrooper.me"
default_language = "en"

generate_feed = true
feed_filename = "rss.xml"
compile_sass = true
build_search_index = false

theme = "zerm"

taxonomies = [
  {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
favicon = "favicon.ico"
og_preview_img = "moleThink112.png"

author = "Mikael Myyrä"
copyright = "Mikael Myyrä"
show_author = false
show_tags = true
show_categories = true
logo_text = "Mole's Nerd Cave"
read_more = "read more"
main_menu = [
  {url="/about/", name="about"},
  {url="/blog/", name="blog"},
  {url="https://twitter.com/moletrooper", name="Twitter", external=true},
  {url="https://github.com/moletrooper", name="GitHub", external=true},
  {url="https://www.artstation.com/moletrooper", name="ArtStation", external=true},
]

# custom color defined in my own sass dir
theme_color = "lime"
center = true
custom_css = true
